### ISSUE TITLE
bug 1366x768 resolution Home layout

### ISSUE THREAD

**Issue by le-xot** [le-xot/games-movies-database#20]
![image](https://github.com/user-attachments/assets/2fea1a6f-4f13-4d35-b3cd-5a3bd868e606)

**Comment by crashmax-dev** [comment]
@Broshe4ka помоги с адаптивом

**Comment by Broshe4ka** [comment]
@crashmax-dev окей босс

**Comment by crashmax-dev** [comment]
resolve #19
